---
title: "P8105 Homework 6 - Tanya Butt (thb2114)"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(patchwork)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r, collapse = TRUE}
birthweight_df = 
  read_csv("birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = as.factor(babysex),
    malform = as.factor(malform),
    frace = as.factor(frace),
    mrace = as.factor(mrace)
  ) %>% 
  select(-c(pnumlbw, pnumsga)) 
```

```{r, collapse = TRUE}
fit_df = 
  birthweight_df %>% 
  select(gaweeks, momage, delwt, wtgain, bwt)

fit = lm(bwt ~ gaweeks + momage + delwt  + wtgain, data = fit_df) 

fit_df %>% 
  add_residuals(fit) %>% 
  add_predictions(fit)

  ggplot(aes(x = wtgain, y = resid)) + geom_point()

fit


```

```{r}
fit_alt_1 = lm(bwt ~ blength + gaweeks, data = birthweight_df) %>% 
  broom::tidy()

fit_alt_1

fit_alt_2 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex +
            blength*babysex + bhead*blength*babysex, data = birthweight_df) %>% 
  broom::tidy()

fit_alt_2
```

## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

set.seed(1)
```

```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps = 
  tibble(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )

boot_straps
```

